[package]
name = "module"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
context = { path = "../context" }
fs_extra = "1.2"
http = { path = "../http" }
libloading = "0.7"
lua = { path = "../lua" }
serde = "1.0"
tempfile = "3.3"
zip = "0.6"
