[package]
name = "locenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.15", features = ["cargo"] }
git2 = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tokio = { version = "1", features = ["full"] }
url = { version = "2", features = ["serde"] }

[dev-dependencies]
tempfile = "3"
