[workspace]
members = [
    "crates/cli",
    "crates/context",
    "crates/fmap",
    "crates/fmap-macros",
    "crates/http",
    "crates/lua",
    "crates/module",
    "crates/script",
    "crates/service",
    "crates/yaml"
]

default-members = ["crates/cli"]
