[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
context = { path = "../context" }
lua = { path = "../lua" }
module = { path = "../module" }
