[package]
name = "locenv"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2"
clap = { version = "3.2", features = ["cargo"] }
context = { path = "../context" }
module = { path = "../module" }
script = { path = "../script" }
service = { path = "../service" }
yaml = { path = "../yaml" }

[build-dependencies]
cc = "1.0"
